server:
  port: 8761

spring:
  application:
    name: service-discovery

eureka:
  client:
    register-with-eureka: false # not register service-discovery-server itself to Eureka
    fetch-registry: false       # not fetch registry information to itself
    response-cache-update-interval-ms: 5000