server:
  port: 8082

spring:
  application:
    name: second-service

eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka # Eureka Server endpoint used to register Eureka client
    fetch-registry: true
    register-with-eureka: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}