global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "user-service"
    metrics_path: "/user-service/actuator/prometheus"
    static_configs:
      - targets:
          - "host.docker.internal:8000"
  - job_name: "order-service"
    metrics_path: "/order-service/actuator/prometheus"
    static_configs:
      - targets:
          - "host.docker.internal:8000"
  - job_name: "apigateway-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "host.docker.internal:8000"
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]